export type Product = {
  id: string
  name: string
  nameFA: string
  description: string
  descriptionFA: string
  price: number
  originalPrice?: number
  category: "engine-oil" | "oil-filter" | "air-filter" | "cabin-filter"
  viscosity?: string
  type?: string
  capacity?: string
  rating: number
  reviews: number
  badge?: string
  badgeFA?: string
  features: string[]
  featuresFA: string[]
  specs?: Record<string, string>
  inStock: boolean
  image: string
}

export const allProducts: Product[] = [
  // Engine Oils
  {
    id: "apex-pro-racing",
    name: "APEX Pro Racing",
    nameFA: "APEX پرو ریسینگ",
    description: "Track-proven formula for high-performance engines. Maximum protection under extreme conditions.",
    descriptionFA: "فرمول تست شده در پیست برای موتورهای پرقدرت. حداکثر محافظت در شرایط سخت.",
    price: 89.99,
    originalPrice: 109.99,
    category: "engine-oil",
    viscosity: "5W-40",
    type: "Full Synthetic",
    capacity: "5L",
    rating: 4.9,
    reviews: 2847,
    badge: "Best Seller",
    badgeFA: "پرفروش",
    features: ["Track Proven", "High Performance", "Extended Protection"],
    featuresFA: ["تست شده در پیست", "عملکرد بالا", "محافظت طولانی"],
    specs: { "API": "SN Plus", "ACEA": "A3/B4", "Viscosity": "5W-40" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1635784065395-c1f00c0c3f60?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "apex-elite-gt",
    name: "APEX Elite GT",
    nameFA: "APEX الیت GT",
    description: "Optimized for fuel economy without compromising protection. Perfect for modern engines.",
    descriptionFA: "بهینه شده برای صرفه‌جویی سوخت بدون کاهش محافظت. مناسب برای موتورهای مدرن.",
    price: 79.99,
    originalPrice: 99.99,
    category: "engine-oil",
    viscosity: "0W-20",
    type: "Full Synthetic",
    capacity: "5L",
    rating: 4.8,
    reviews: 1923,
    badge: "Eco Choice",
    badgeFA: "انتخاب اقتصادی",
    features: ["Fuel Economy", "Low Emissions", "Modern Engines"],
    featuresFA: ["صرفه‌جویی سوخت", "آلایندگی کم", "موتورهای مدرن"],
    specs: { "API": "SN Plus", "ILSAC": "GF-6", "Viscosity": "0W-20" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "apex-extreme",
    name: "APEX Extreme",
    nameFA: "APEX اکستریم",
    description: "Racing formula for extreme heat and high-RPM applications. Motorsport grade protection.",
    descriptionFA: "فرمول مسابقه برای گرمای شدید و دور بالا. محافظت درجه موتوراسپرت.",
    price: 129.99,
    originalPrice: 159.99,
    category: "engine-oil",
    viscosity: "10W-60",
    type: "Racing Formula",
    capacity: "5L",
    rating: 5.0,
    reviews: 987,
    badge: "Premium",
    badgeFA: "ممتاز",
    features: ["Extreme Heat", "Motorsport Grade", "High RPM"],
    featuresFA: ["گرمای شدید", "درجه موتوراسپرت", "دور بالا"],
    specs: { "API": "SN", "ACEA": "A3/B4", "Viscosity": "10W-60" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "apex-winter-guard",
    name: "APEX Winter Guard",
    nameFA: "APEX وینتر گارد",
    description: "Arctic-tested formula for cold climate conditions. Instant protection from first start.",
    descriptionFA: "فرمول تست شده در قطب شمال برای آب و هوای سرد. محافظت فوری از اولین استارت.",
    price: 74.99,
    originalPrice: 94.99,
    category: "engine-oil",
    viscosity: "0W-40",
    type: "Full Synthetic",
    capacity: "5L",
    rating: 4.7,
    reviews: 1456,
    badge: "Cold Climate",
    badgeFA: "آب و هوای سرد",
    features: ["Arctic Tested", "Quick Start", "Cold Protection"],
    featuresFA: ["تست قطب شمال", "استارت سریع", "محافظت سرما"],
    specs: { "API": "SN Plus", "ACEA": "A3/B4", "Viscosity": "0W-40" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "apex-touring",
    name: "APEX Touring",
    nameFA: "APEX توریینگ",
    description: "Balanced formula for everyday driving. Long-lasting protection for all conditions.",
    descriptionFA: "فرمول متوازن برای رانندگی روزانه. محافظت طولانی برای همه شرایط.",
    price: 69.99,
    originalPrice: 84.99,
    category: "engine-oil",
    viscosity: "5W-30",
    type: "Full Synthetic",
    capacity: "5L",
    rating: 4.6,
    reviews: 2341,
    badge: "Daily Driver",
    badgeFA: "استفاده روزانه",
    features: ["Everyday Use", "All Conditions", "Long Life"],
    featuresFA: ["استفاده روزانه", "همه شرایط", "عمر طولانی"],
    specs: { "API": "SN Plus", "ILSAC": "GF-5", "Viscosity": "5W-30" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "apex-diesel-pro",
    name: "APEX Diesel Pro",
    nameFA: "APEX دیزل پرو",
    description: "Specially formulated for diesel engines. Superior soot handling and protection.",
    descriptionFA: "فرمول ویژه برای موتورهای دیزل. مدیریت برتر دوده و محافظت.",
    price: 94.99,
    originalPrice: 114.99,
    category: "engine-oil",
    viscosity: "5W-40",
    type: "Diesel Formula",
    capacity: "5L",
    rating: 4.8,
    reviews: 1123,
    badge: "Diesel",
    badgeFA: "دیزل",
    features: ["Diesel Engines", "Soot Control", "DPF Compatible"],
    featuresFA: ["موتور دیزل", "کنترل دوده", "سازگار با DPF"],
    specs: { "API": "CK-4", "ACEA": "C3", "Viscosity": "5W-40" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=400&h=400&fit=crop&crop=center",
  },

  // Oil Filters
  {
    id: "filter-oil-premium",
    name: "APEX Premium Oil Filter",
    nameFA: "فیلتر روغن پریمیوم APEX",
    description: "High-efficiency filtration with 99% dirt capture. Extended service life.",
    descriptionFA: "فیلتراسیون با کارایی بالا با ۹۹٪ جذب آلودگی. عمر سرویس طولانی.",
    price: 24.99,
    originalPrice: 29.99,
    category: "oil-filter",
    rating: 4.8,
    reviews: 1876,
    badge: "Premium",
    badgeFA: "ممتاز",
    features: ["99% Filtration", "Extended Life", "Anti-Drain Back"],
    featuresFA: ["۹۹٪ فیلتراسیون", "عمر طولانی", "ضد بازگشت"],
    specs: { "Efficiency": "99%", "Life": "15,000 km", "Type": "Spin-on" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-oil-racing",
    name: "APEX Racing Oil Filter",
    nameFA: "فیلتر روغن ریسینگ APEX",
    description: "High-flow design for performance applications. Maximum protection at high RPM.",
    descriptionFA: "طراحی جریان بالا برای کاربردهای ورزشی. حداکثر محافظت در دور بالا.",
    price: 34.99,
    originalPrice: 42.99,
    category: "oil-filter",
    rating: 4.9,
    reviews: 723,
    badge: "Racing",
    badgeFA: "ریسینگ",
    features: ["High Flow", "Racing Grade", "High RPM"],
    featuresFA: ["جریان بالا", "درجه مسابقه", "دور بالا"],
    specs: { "Efficiency": "99.5%", "Flow Rate": "High", "Type": "Spin-on" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-oil-economy",
    name: "APEX Standard Oil Filter",
    nameFA: "فیلتر روغن استاندارد APEX",
    description: "Reliable filtration for everyday driving. Quality protection at great value.",
    descriptionFA: "فیلتراسیون قابل اعتماد برای رانندگی روزانه. محافظت با کیفیت و قیمت مناسب.",
    price: 14.99,
    originalPrice: 19.99,
    category: "oil-filter",
    rating: 4.5,
    reviews: 3421,
    badge: "Value",
    badgeFA: "ارزشی",
    features: ["Reliable", "Everyday Use", "Great Value"],
    featuresFA: ["قابل اعتماد", "استفاده روزانه", "ارزش عالی"],
    specs: { "Efficiency": "97%", "Life": "10,000 km", "Type": "Spin-on" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-oil-euro",
    name: "APEX Euro Oil Filter",
    nameFA: "فیلتر روغن یورو APEX",
    description: "Designed for European vehicles. OE-quality replacement filter.",
    descriptionFA: "طراحی شده برای خودروهای اروپایی. فیلتر جایگزین با کیفیت OE.",
    price: 29.99,
    originalPrice: 36.99,
    category: "oil-filter",
    rating: 4.7,
    reviews: 1234,
    badge: "Euro Spec",
    badgeFA: "مشخصات اروپا",
    features: ["European Cars", "OE Quality", "Cartridge Type"],
    featuresFA: ["خودروهای اروپایی", "کیفیت OE", "نوع کارتریج"],
    specs: { "Efficiency": "99%", "Type": "Cartridge", "Fits": "BMW/Mercedes/VW" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=400&fit=crop&crop=center",
  },

  // Air Filters
  {
    id: "filter-air-performance",
    name: "APEX Performance Air Filter",
    nameFA: "فیلتر هوای پرفورمنس APEX",
    description: "High-flow cotton gauze filter. Reusable and washable for lifetime use.",
    descriptionFA: "فیلتر گاز پنبه‌ای با جریان بالا. قابل استفاده مجدد و قابل شستشو برای عمر طولانی.",
    price: 59.99,
    originalPrice: 74.99,
    category: "air-filter",
    rating: 4.9,
    reviews: 1567,
    badge: "Performance",
    badgeFA: "پرفورمنس",
    features: ["High Flow", "Reusable", "Lifetime Warranty"],
    featuresFA: ["جریان بالا", "قابل استفاده مجدد", "گارانتی مادام‌العمر"],
    specs: { "Material": "Cotton Gauze", "Flow": "+15%", "Type": "Washable" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-air-standard",
    name: "APEX Standard Air Filter",
    nameFA: "فیلتر هوای استاندارد APEX",
    description: "OE-quality paper air filter. Maximum dust and debris protection.",
    descriptionFA: "فیلتر هوای کاغذی با کیفیت OE. حداکثر محافظت در برابر گرد و غبار.",
    price: 24.99,
    originalPrice: 32.99,
    category: "air-filter",
    rating: 4.6,
    reviews: 2876,
    badge: "Standard",
    badgeFA: "استاندارد",
    features: ["OE Quality", "Paper Element", "High Filtration"],
    featuresFA: ["کیفیت OE", "المان کاغذی", "فیلتراسیون بالا"],
    specs: { "Material": "Paper", "Efficiency": "99%", "Type": "Disposable" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-air-heavy-duty",
    name: "APEX Heavy Duty Air Filter",
    nameFA: "فیلتر هوای هوی دیوتی APEX",
    description: "For trucks and SUVs. Enhanced capacity for dusty conditions.",
    descriptionFA: "برای کامیون‌ها و SUVها. ظرفیت بهبود یافته برای شرایط گرد و غباری.",
    price: 39.99,
    originalPrice: 49.99,
    category: "air-filter",
    rating: 4.7,
    reviews: 987,
    badge: "Heavy Duty",
    badgeFA: "هوی دیوتی",
    features: ["Trucks/SUVs", "High Capacity", "Dusty Conditions"],
    featuresFA: ["کامیون/SUV", "ظرفیت بالا", "شرایط گرد و غباری"],
    specs: { "Material": "Multi-Layer Paper", "Capacity": "2x Standard", "Type": "Disposable" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&h=400&fit=crop&crop=center",
  },

  // Cabin Filters
  {
    id: "filter-cabin-carbon",
    name: "APEX Carbon Cabin Filter",
    nameFA: "فیلتر کابین کربن APEX",
    description: "Activated carbon filter for odor and gas absorption. Premium air quality.",
    descriptionFA: "فیلتر کربن فعال برای جذب بو و گاز. کیفیت هوای ممتاز.",
    price: 34.99,
    originalPrice: 44.99,
    category: "cabin-filter",
    rating: 4.8,
    reviews: 1654,
    badge: "Premium",
    badgeFA: "ممتاز",
    features: ["Activated Carbon", "Odor Removal", "Gas Absorption"],
    featuresFA: ["کربن فعال", "حذف بو", "جذب گاز"],
    specs: { "Material": "Activated Carbon", "Odor": "Yes", "Allergen": "Yes" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-cabin-standard",
    name: "APEX Standard Cabin Filter",
    nameFA: "فیلتر کابین استاندارد APEX",
    description: "Particulate cabin filter for dust and pollen. Clean cabin air.",
    descriptionFA: "فیلتر کابین ذره‌ای برای گرد و غبار و گرده. هوای تمیز کابین.",
    price: 19.99,
    originalPrice: 24.99,
    category: "cabin-filter",
    rating: 4.5,
    reviews: 3234,
    badge: "Standard",
    badgeFA: "استاندارد",
    features: ["Particulate Filter", "Dust/Pollen", "Clean Air"],
    featuresFA: ["فیلتر ذره‌ای", "گرد و غبار/گرده", "هوای تمیز"],
    specs: { "Material": "Non-woven", "Dust": "99%", "Pollen": "Yes" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&h=400&fit=crop&crop=center",
  },
  {
    id: "filter-cabin-hepa",
    name: "APEX HEPA Cabin Filter",
    nameFA: "فیلتر کابین هپا APEX",
    description: "Hospital-grade HEPA filtration. Captures 99.97% of particles.",
    descriptionFA: "فیلتراسیون هپا با درجه بیمارستانی. جذب ۹۹.۹۷٪ ذرات.",
    price: 49.99,
    originalPrice: 59.99,
    category: "cabin-filter",
    rating: 4.9,
    reviews: 876,
    badge: "HEPA",
    badgeFA: "هپا",
    features: ["HEPA Grade", "99.97% Capture", "Allergen Free"],
    featuresFA: ["درجه هپا", "۹۹.۹۷٪ جذب", "بدون آلرژن"],
    specs: { "Material": "HEPA Media", "Efficiency": "99.97%", "Virus": "Yes" },
    inStock: true,
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400&h=400&fit=crop&crop=center",
  },
]

export function getProductsByCategory(category: Product["category"]) {
  return allProducts.filter(p => p.category === category)
}

export function getProductById(id: string) {
  return allProducts.find(p => p.id === id)
}
